### ISSUE TITLE
添加 Github Action 以进行更简单的版本管理

### ISSUE THREAD

**Issue by newbe36524** [xljiulang/FastGithub#10]
- [x] 集成 release-drafter
- [x] 集成 Labeler
- [x] PR 编译检查

**Comment by xljiulang** [comment]
目前项目简单，这个用不上

**Comment by newbe36524** [comment]
pr 已经完成
后续发版本流程：

- 你可以通过 PR 向主分支提交变更，并且使用标题表示变更的内容
- 这将会自动创建 drafter release
- 当你觉得已经可以发布版本的时候，可以将 drafter release 进行 publish。 按照 vx.x.x 的格式进行版本编号。
- github action 将会自动打包，将压缩包附加到 release 中。

see #11

**Comment by xljiulang** [comment]
666

**Comment by xljiulang** [comment]
tagName可以不包含v字头吗，因为既有的发布版本里，用tagName来做版本比较远程升级提示。

**Comment by xljiulang** [comment]
感谢提交，我消化一个这个是怎么怎么编译的。我现在找不到你自动创建 drafter release的例子了，因为想确切那些zip包是否OK，主是dnscrypt-proxy二进制文件的打包：见 [FastGithub.DomainResolve.csproj}(https://github.com/xljiulang/FastGithub/blob/master/FastGithub.DomainResolve/FastGithub.DomainResolve.csproj) 目前项目文件里没有区分平台来引入。

**Comment by newbe36524** [comment]
1. 管理员可以在 release 页面查看 drafter release

<img width="947" alt="msedge_mccPZ9f1ON" src="https://user-images.githubusercontent.com/7685462/126890743-6869db6a-920f-424e-a666-0d8a9d73ff86.png">

2.  分平台引入，这个目测你需要在 csproj 中加入 Condition= $(RuntimeIdentifier) == ‘win-x64’ 来区分引入

**Comment by xljiulang** [comment]
$(RuntimeIdentifier)总是为empty

**Comment by newbe36524** [comment]
这不科学
https://stackoverflow.com/questions/65160131/what-msbuild-condition-should-be-used-to-detect-target-os

**Comment by xljiulang** [comment]
```
	<ItemGroup Condition="'$(RuntimeIdentifier)' == 'win-x64'">
		<None Update="dnscrypt-proxy.exe">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup Condition="'$(RuntimeIdentifier)' == 'linux-x64'">
		<None Update="dnscrypt-proxy">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
```
然后dotnet publish，目标里没有拷贝

**Comment by xljiulang** [comment]
但是在vs的项目属性看上去是正确的。

**Comment by xljiulang** [comment]
还有一个问题，zip之前，在非windows，需要对相关的可执行文件修改为可执行属性吧。

**Comment by xljiulang** [comment]
我觉得把这些问题合在action里一同解决，正是加入这个action的意义

**Comment by newbe36524** [comment]
- 据我所知。可执行属性是下载之后才能变更的。没有提前变更的办法
- rid 必须先指定默认值，才能覆盖，真是神圣的屎 https://github.com/dotnet/sdk/issues/10625

**Comment by xljiulang** [comment]
tar打包，是可以将文件属性保持的，打包之前设置好就行

**Comment by xljiulang** [comment]
linux可以整tar.gz格式

**Comment by newbe36524** [comment]
@xljiulang 
1. 用 tar.gz，简单
2. 要修改哪个的属性。 dnscrypt-proxy 还是 FastGithub

**Comment by xljiulang** [comment]
经过考虑，当前暂时先移除了github action功能，主要原因是相关的脚本还有一些问题或不完善。

目前退回到shell发布：[pack.sh](https://github.com/xljiulang/FastGithub/blob/master/FastGithub/pack.sh)
问题修复见：[fix repository owner](https://github.com/xljiulang/FastGithub/commit/50f11685be899de035b78a7f910344dc0a233907)

**Comment by newbe36524** [comment]
这当然可以
