### ISSUE TITLE
能增加一个*.github.io的解析吗？

### ISSUE THREAD

**Issue by kingreatwill** [xljiulang/FastGithub#3]
如题，*.github.io也经常需要自己找ip解析，并且对应的二级域名都需要添加hosts文件

**Comment by xljiulang** [comment]
你在配置文件里加入就可以了：加入域名，还有域名的http扫描路径

**Comment by kingreatwill** [comment]
@xljiulang 好的，但是不能解析所有的（已访问的）*.github.io

**Comment by xljiulang** [comment]
域名的扫描检测规则需要手动配置，所以做被动支持动态域名。

**Comment by xljiulang** [comment]
新版本已支持*.github.io的解析
