### ISSUE TITLE
此项目的思路不能有效解决

### ISSUE THREAD

**Issue by cjh0613** [xljiulang/FastGithub#6]
现在的封锁方法是间歇tcp重置，此项目的思路不能有效解决访问问题。

**Comment by xljiulang** [comment]
不同网络环境不一样的，这个目前能满足dns污染的网络。但有些网络会遇到client hello引发tcp rst，主要是由于sni明文的原因 ，目前无解。

**Comment by xljiulang** [comment]
不同网络环境不一样的，这个目前能满足dns污染的网络。但有些网络会遇到client hello引发tcp rst，主要是由于sni明文的原因 ，目前无解。

**Comment by xljiulang** [comment]
@cjh0613 tcp rst的解决方案，NoneSni分支在开发中，你可以迁出该分支的代码自行编译测试效果。

**Comment by xljiulang** [comment]
1.0.3已解决
