### ISSUE TITLE
有报错

### ISSUE THREAD

**Issue by apgk** [xljiulang/FastGithub#8]
1.打开软件有个错误：
warn: FastGithub.Upgrade.UpgradeHostedService[0]
      升级失败：The SSL connection could not be established, see inner exception
2.打开github，经常被爆隐私问题

**Comment by apgk** [comment]
还有应该设定 关闭软件时清除设定127.0.0.1 dns ，经常引起网页访问问题

**Comment by xljiulang** [comment]
1和2是因为你没有安装根证书出现的；
程序正常停止时，会移除127.0.0.1，就算移除失败，操作系统会自动用备用dns
